languageCode = "en-us"
title = "telemetR docs"
baseurl = "http://example.org/"
theme = "hugo-theme-learn"
publishDir = "docs"

[params]
  description = "Documentation for telemetR DMS"
  author = "Mitchell Gritts"
  menu = ["introduction", "telemetr-db", "telemetr-generator", "telemetr-api"]
